---
#permalink: quickstart3_chap_install_overview.html
layout: page
---
:sectnums:
:sectanchors:

== Get started with &susemgr;
 3 by setting up a KVM learning environment.
This quick-start guide will provide you with introductory guidance on setting up &susemgr;
server.
You will learn the basics of managing both traditional &susemgr;
clients and Salt clients.
This guide is intended for system administrators.

[[_quickstart.sect.introduction]]

== Introducing &susemgr;

&susemgr;
lets you efficiently manage large sets of Linux systems and keep them up to date.
It provides automated and cost-effective software management, asset management, and system provisioning. &susemgr;
provides a best in class solution for organizations requiring absolute control of maintenance and package deployment on their servers.
It allows customers the highest level of flexibility and power ensuring their servers remain secure while facilitating and advancing an organizations system life-cycle requirements.

.Salt
The inclusion of [path]_Salt_
 in &susemgr;
 3 provides powerful event-driven configuration and management capabilities for fine grained control of any modern infrastructure.

.Salt-master
&susemgr;&productnumber;
takes a commanding role as a Salt-master capable of orchestrating thousands of Salt-minions (&susemgr;
Clients) via remote execution.

.Distribution Management
&susemgr;&productnumber;
is also fully compatible with Red Hat Satellite Server and offers seamless management of both &sle;
and &rhel;
client systems.

[[_quickstart.sect.bird.eye.view]]
== Overview

&susemgr;
may be integrated within your network infrastructure in multiple ways.
In this guide you will perform the following steps for an initial test setup.

* Install SLES12 and SUSE Manager as an extension
* Register SUSE Manager server with SCC (SUSE Customer Center)
* Synchronize a repository channel for use with both traditional clients and salt-minions
* Create an authentication key to act as an ID for the synced repository channel
* Add the new authentication key to a bootstrap template script and connect a traditional client
* Register a salt-minion with SUSE Manager (salt-master) and assign it a channel with an authentication key


[[_quickstart.sect.prerequisites.install]]
== Prerequisites for Installation


This guide requires that you have created an account with SCC (&scc;
). During installation of both &sls;
 12 and &susemgr;&productnumber;
, &scc;
credentials will be requested and you must enter them to receive the latest packages and updates.
The following procedure will guide you through obtaining your SCC [path]_Organizational Credentials_
.

.Procedure: Obtaining Your SCC Organization Credentials
. Open a browser and direct it to https://scc.suse.com/login.
. If you have not done so, create an account now.
. Log in to your new SCC account.
. Under the [path]_Management tools_ widget select [path]_Manage Users_ .
. Click the [path]_Organization Credentials_ tab.
. Keep this information handy during &susemgr; 3 setup.


== Obtaining Installation Media


After logging into your SCC account, you can find the installation images provided at the following addresses.
Select one and continue reading:

.Just Enough Operating System (JeOS) vs. Full Media Image
[NOTE]
====
The SLES 12 JeOS image provides the quickest route for setup of a test environment.
The JeOS image total size is about 240 MB.
The alternative would be the 3 GB &sls;
 12 DVD image.
Both installation media are appropriate, but depend upon available bandwidth or your application needs.
Both methods of installation will be covered in this guide.
====
** Just Enough Operating System (JeOS) 240 MB https://www.suse.com/products/server/jeos/
** SLES 12 DVD image 3 GB https://www.suse.com/products/server/download/


[[_quickstart.sect.software.requirements]]
== Hardware Requirements


Review the following table for &susemgr;
hardware and software requirements.
For installation on &zsystems;
, see <<_art.suma.install.zsystems>>
.

[cols="1,1", options="header"]
|===
|

        Hardware


|

        Recommended




|

CPU
|

Multi-core 64-bit CPU (x86_64)

|

RAM
|

Minimum 4&nbsp;
GB+ for test server

Minimum 16&nbsp;
GB+ for base installation

Minimum 32&nbsp;
GB+ for a production server

|

Free Disk Space
|

Minimum 100&nbsp;
GB for root partition

_For the purposes of this guide the default JeOS root
        partition size of 24 GB will be sufficient_

Minimum 50&nbsp;
GB for [path]_/var/lib/pgsql_

Minimum 50&nbsp;
GB per SUSE product + 100 GB per Red Hat product [path]_/var/spacewalk_
|===

== Base Host OS


SUSE Manager is based on the following host OS.

.Version Information
[NOTE]
====
&susemgr;
 3.1 was originally released as a SLES 12 SP2 extension.
With the next maintenance update (2017), &susemgr;
 3.1 will be based on SLES 12 SP3 and it will support SLE 12 SP3 clients officially.
In the following sections and chapters, it is highly recommended to use SLE 12 SP3 instead of SP2.
====

[cols="1,1", options="header"]
|===
|
       Base OS

|
       SUSE Manager Version



|

SLES 12 SP3
|

3.0, 3.1
|===

[[_mgr.supported.client.systems]]
== Supported Client Systems


Clients with the following operating systems are supported for registration with &susemgr;
.
If you plan on using the new Salt features, ensure your clients are supported.

.Supported Versions and SP Levels
[NOTE]
====
Client operating system versions and SP levels must be under general support (normal or LTSS) to be supported with &susemgr;
.
For details, see https://www.suse.com/lifecycle.
====

[cols="1,1,1,1", options="header"]
|===
|

        Operating Systems


|

        Architecture


|

        Traditional Clients


|

        Salt Clients




|

&sle;
 11 SP4 LTSS
|

&x86;
, &x86;
_64, &ipf;
, IBM &ppc;
, &zseries;
|

Supported
|

Supported

|

&sle;
 12 SP1, SP2, SP3
|

&x86;
_64, IBM &power;
(&ppc64le;
), &zseries;
|

Supported
|

Supported

|

&rhel;
 5
|

&x86;
, &x86;
_64
|

Supported
|

Unsupported

|

&rhel;
 6
|

&x86;
, &x86;
_64
|

Supported
|

Supported

|

&rhel;
 7
|

&x86;
, &x86;
_64
|

Supported
|

Supported

|

Novell Open Enterprise Server 11, SP1, SP2, SP3 LTSS
|

&x86;
, &x86;
_64
|

Supported
|

Supported
|===

[[_mgr.additional.requirements]]
== Additional Requirements


To successfully complete this guide some network requirements must be met.
The following section will walk you through these requirements.

.Fully Qualified Domain Name (FQDN):
The &susemgr;
server must resolve its FQDN correctly or cookies will not work properly on the &webui;
.
For more information on FQDN, see:
** https://www.suse.com/documentation/sles-12/book_sle_admin/data/sec_basicnet_yast.html#sec_basicnet_yast_change_host


.Hostname and IP Address:
To ensure that &susemgr;
's domain name can be resolved by its clients, both server and client machines must be connected to a working Domain Name System (DNS) server.
This guide assumes the required infrastructure exists within your environment.
For more information on setting up a (DNS) server, see:

.Using a Proxy When Installing from &sle;Media
If you are on an internal network and do not have access to &scc;
, you can setup and use a proxy during a &sle;
installation.
For more information on configuring a proxy for access to &scc;
during a &sle;
installation see:https://www.suse.com/documentation/sled-12/singlehtml/book_sle_deployment/book_sle_deployment.html#sec.i.yast2.start.parameters.proxy
** https://www.suse.com/documentation/sles-12/book_sle_admin/data/cha_dns.html


.Naming Your Server
[IMPORTANT]
====
The hostname of &susemgr;
must not contain uppercase letters as this may cause [path]_jabberd_
 to fail.
Choose the hostname of your &susemgr;
 server carefully.
Although changing the server name is possible, it is a complex process and unsupported.
====


For a more complete overview on &susemgr;
requirements not covered in this guide, see <<_mgr.conceptual.overview>>
.

== Firewall Rules


In a production environment &susemgr;
server and its clients should always utilize firewall rules.
The following table provides an overview of required ports for use by &susemgr;
 3.1.

Traditional client systems connect to &susemgr;
via port 443. In addition, enabling push actions from &susemgr;
to client systems, requires inbound connections on port 5222.
If &susemgr;
will also push to a &susemgr;
proxy, you must allow inbound connections on port 5269.

.Required Ports on &susemgr;Server
[cols="1,1,1", options="header"]
|===
|

        Port


|

        Direction


|

        Reason



|

67
|

Inbound
|

Required when configured as a DHCP server for systems requesting IP addresses.

|

69
|

Inbound
|

Used when configured as a PXE server and allows installation and re-installation of PXE-boot enabled systems.

|

80
|

Outbound
|

Used to contact &scc;
.

|

443
|

Inbound
|

All &webui;
, traditional client, and proxy server requests and &susemgr;
uses this port for &scc;
inbound traffic.

|

4505
|

Inbound
|

Required by the Salt-master to accept communication requests via TCP from minions.

|

4506
|

Inbound
|

Required by the Salt-master to accept communication requests via TCP from minions.

|

5222
|

Inbound
|

When you wish to push actions to clients this port is required by the [path]_osad_
 daemon running on the client systems.

|

5269
|

Inbound/Outbound
|

Needed if you push actions to or via a &susemgrproxy;
.

|


|

Outbound
|

Squid HTTP proxy for outgoing connections.
It could be any port you configure.
|===
