---
permalink: manager-index.html
layout: page
---
:showtitle:
:page-title:
:page-description: SUSE Manager Documentation

== Documentation Editions

This page contains links to upstream/downstream builds from the SUSE Manager documentation source code repository.

=== Latest Development Edition (Upstream)

Latest builds are triggered automatically once a pull request has been accepted by a SUSE Technical Writer. Keep in mind these documents are living works in progress and will contain bugs and incomplete sections and procedures. Use of these development documents is performed at _your own risk_.


<<manager31-index.adoc#manager31-index, SUSE Manager 3.1>>

=== Enterprise Editions (Downstream)

The following enterprise documentation links represents documentation which has passed through extensive testing and QA procedures. It is verified and reliable. Bugs which are submitted by community and fixed in the latest develop edition will be applied to downstream enterprise documentation branches if applicable.


https://www.suse.com/documentation/suse-manager-3/book_suma3_quickstart_3/data/quickstart_chapt_overview_requirements.html[SUSE Manager 3.0 Getting Started, role="external", window="_blank"]

https://www.suse.com/documentation/suse-manager-3/book_suma_reference_manual_3/data/book_suma_reference_manual_3.html[SUSE Manager 3.0 Reference Manual, role="external", window="_blank"]
